### ISSUE TITLE
[FEATURE REQUEST] Removing frames around keyframes to make for faster transitions

### ISSUE THREAD

**Issue by phr00t** [kijai/ComfyUI-DynamiCrafterWrapper#10]
Right now, lots of frames are made right around middle keyframes, causing significant pauses in the motion that might not be desired. I think there should be an option to remove frames around keyframes in the middle of the animation. For example:

![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/5983470/0d368202-4710-47d0-81c7-379d0966557a)

6 or 7 of the frames in the middle are nearly identical, so she doesn't transition smoothly from grabbing her hat and taking it off. I may tackle try and tackle this one myself.

**Comment by kijai** [comment]
Merged your PR now so this can be closed, thank you!
