### ISSUE TITLE
Looping condition

### ISSUE THREAD

**Issue by edwinzeng2005** [kijai/ComfyUI-DynamiCrafterWrapper#14]
Is there a boolean condition to enable/disable looping?

**Comment by kijai** [comment]
> Is there a boolean condition to enable/disable looping?

The looping feature is realized simply by using the interpolation model and inputting same image to image1 and image2.

**Comment by edwinzeng2005** [comment]
I see. The basic non-looping process works by setting only 1 image as the input.
