### ISSUE TITLE
 Add a "Image Resolution Standardization" node.

### ISSUE THREAD

**Issue by hben35096** [kijai/ComfyUI-DynamiCrafterWrapper#18]
Hi，May I ask if it's possible to add an image scaling node that can standardize the resolution of the image to be scaled, in order to avoid situations like the following after scaling?

```
Error occurred when executing VHS_VideoCombine:

An error occured in the ffmpeg subprocess:
[libx264 @ 0x55cb2a2dedc0] width not divisible by 2 (759x1024)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height


File "/mnt/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/mnt/workspace/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/mnt/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 358, in combine_video
output_process.send(images.tobytes())
File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 130, in ffmpeg_process
raise Exception("An error occured in the ffmpeg subprocess:\n" \

```
I think the image preprocessing method like the one in the official demo is also good, filling the sides of the image with black to make the resolution of the image standardized. Of course, in Comfyui, this resolution can be relatively free, as long as it is a multiple of 32 (not sure, maybe multiples of 16 are also acceptable?).

**Comment by kijai** [comment]
You can use this node from ComfyUI-Essentials: 
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/40791699/97d7ba83-f14f-402f-8fa8-a89886c53ed5)

I'll also add simple check for divisible by 2 as there's no point for it not to ever be.

**Comment by kijai** [comment]
This should now be automated within the node, so closing this issue.
