### ISSUE TITLE
How to use your updated bf16 pruned models? 

### ISSUE THREAD

**Issue by luke-evans-liu** [kijai/ComfyUI-DynamiCrafterWrapper#25]
How to use your updated bf16 pruned models? But from my experience, it causes a significant increase in GPU memory usage and extremely slow speed. Is there any trick to use it more efficiently? Or do I need to modify the code? Thanks.

**Comment by kijai** [comment]
Use them with these nodes? Only time I had those issues was when running without xformers, it seems to be required.

**Comment by luke-evans-liu** [comment]
But I have already installed xformers

**Comment by luke-evans-liu** [comment]
Additionally, how can I enable the bf16 format to take effect?

**Comment by luke-evans-liu** [comment]
I am not sure whether the bf16 format is currently in effect.
