### ISSUE TITLE
Request to add a video resolution option

### ISSUE THREAD

**Issue by hben35096** [kijai/ComfyUI-DynamiCrafterWrapper#3]
Although the official requirement is a fixed width and height, I have tried, for example, to change:
576 wide, 1024 high.
The effect is also okay.

https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/139383150/9ebaff81-7b24-42c1-86e5-c05154d2cc7e

**Comment by kijai** [comment]
The resolution with the node is not fixed at all, it uses the resolution of your input image directly.

**Comment by hben35096** [comment]
> The resolution with the node is not fixed at all, it uses the resolution of your input image directly. There are lots of other nodes to handle the resizing if necessary.

Thanks, I'll try it right away, I've been waiting for this plugin to come out, thank you
