### ISSUE TITLE
Error occurred when executing DynamiCrafterModelLoader:

### ISSUE THREAD

**Issue by EvanZouQ** [kijai/ComfyUI-DynamiCrafterWrapper#34]
Error occurred when executing DynamiCrafterModelLoader:

An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\nodes.py", line 82, in loadmodel
self.model = instantiate_from_config(model_config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\utils\utils.py", line 33, in instantiate_from_config
return get_obj_from_str(config["target"])(**config.get("params", dict()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\models\ddpm3d.py", line 680, in __init__
super().__init__(*args, **kwargs)
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\models\ddpm3d.py", line 414, in __init__
self.instantiate_cond_stage(cond_stage_config)
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\models\ddpm3d.py", line 447, in instantiate_cond_stage
model = instantiate_from_config(config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\utils\utils.py", line 33, in instantiate_from_config
return get_obj_from_str(config["target"])(**config.get("params", dict()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\lvdm\modules\encoders\condition.py", line 188, in __init__
model, _, _ = open_clip.create_model_and_transforms(arch, device=torch.device('cpu'), pretrained=version)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\factory.py", line 324, in create_model_and_transforms
model = create_model(
^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\factory.py", line 231, in create_model
checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\pretrained.py", line 434, in download_pretrained
target = download_pretrained_from_hf(model_id, cache_dir=cache_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\open_clip\pretrained.py", line 404, in download_pretrained_from_hf
cached_file = hf_hub_download(model_id, filename, revision=revision, cache_dir=cache_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1221, in hf_hub_download
return _hf_hub_download_to_cache_dir(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1325, in _hf_hub_download_to_cache_dir
_raise_on_head_call_error(head_call_error, force_download, local_files_only)
File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1826, in _raise_on_head_call_error
raise LocalEntryNotFoundError(

**When I try the workflow in ComfyUI, this error always occur. Can anyone help me? Mnay thanks.**

**Comment by kijai** [comment]
This has to do with loading the open_clip model, by default it's autodownloaded, which can fail in some circumstances. 

I added a node to select a local file to load instead, which could help if you are able to download it from here:

https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/blob/main/open_clip_pytorch_model.bin

to `ComfyUI/clip_vision` -folder

![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/40791699/5e8cdcb1-8c54-4b78-aa61-c2d9da9804f1)

**Comment by EvanZouQ** [comment]
> This has to do with loading the open_clip model, by default it's autodownloaded, which can fail in some circumstances.
> 
> I added a node to select a local file to load instead, which could help if you are able to download it from here:
> 
> https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/blob/main/open_clip_pytorch_model.bin
> 
> to `ComfyUI/clip_vision` -folder
> 
> ![image](https://private-user-images.githubusercontent.com/40791699/331589226-5e8cdcb1-8c54-4b78-aa61-c2d9da9804f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTM0MTMsIm5iZiI6MTcxNTk1MzExMywicGF0aCI6Ii80MDc5MTY5OS8zMzE1ODkyMjYtNWU4Y2RjYjEtOGM1NC00Yjc4LWFhNjEtYzJkOWRhOTgwNGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOTNiMDEzZWE5ZGIzZmYwYTk2OWFkNjZlNGU0MTFkMGUwNzA3N2NjYjE5ZjFjZWYxNjFlNjVmZjQwYzQ4YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QoaO_RMfoBvx7_Sn8IhzstmuZpxutDyCu5Ofzm00iaI)

Dear kijai, I am sorry that I cannot find the node 'OpenCLIPVisionSelect'. Meanwhile, there is no access of 'opt_openclippath', as shown in the figure. Can you help me? Thanks you very much. 
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/65980596/0e61313f-7e3f-46df-89c0-fbd87d456c1f)

**Comment by kijai** [comment]
> > This has to do with loading the open_clip model, by default it's autodownloaded, which can fail in some circumstances.
> > I added a node to select a local file to load instead, which could help if you are able to download it from here:
> > https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/blob/main/open_clip_pytorch_model.bin
> > to `ComfyUI/clip_vision` -folder
> > ![image](https://private-user-images.githubusercontent.com/40791699/331589226-5e8cdcb1-8c54-4b78-aa61-c2d9da9804f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTM0MTMsIm5iZiI6MTcxNTk1MzExMywicGF0aCI6Ii80MDc5MTY5OS8zMzE1ODkyMjYtNWU4Y2RjYjEtOGM1NC00Yjc4LWFhNjEtYzJkOWRhOTgwNGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOTNiMDEzZWE5ZGIzZmYwYTk2OWFkNjZlNGU0MTFkMGUwNzA3N2NjYjE5ZjFjZWYxNjFlNjVmZjQwYzQ4YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QoaO_RMfoBvx7_Sn8IhzstmuZpxutDyCu5Ofzm00iaI)
> 
> Dear kijai, I am sorry that I cannot find the node 'OpenCLIPVisionSelect'. Meanwhile, there is no access of 'opt_openclippath', as shown in the figure. Can you help me? Thanks you very much. ![image](https://private-user-images.githubusercontent.com/65980596/331616945-0e61313f-7e3f-46df-89c0-fbd87d456c1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTQyODcsIm5iZiI6MTcxNTk1Mzk4NywicGF0aCI6Ii82NTk4MDU5Ni8zMzE2MTY5NDUtMGU2MTMxM2YtN2UzZi00NmRmLTg5YzAtZmJkODdkNDU2YzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzNTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NjA4YjFiZDNlMGMyNjk5MmRmM2RkNzJmYjQxMDU0ODEwYjQ4N2NlY2Y3MTY3NDc5YjljMGYwMmFjYWVmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bm2B5ePc6PkeQSlJfGhN0c1lgXQkGr7gJEpVNKxCaT0)

I mean I literally just added it, so you would need to update this node pack.

**Comment by EvanZouQ** [comment]
> > > This has to do with loading the open_clip model, by default it's autodownloaded, which can fail in some circumstances.
> > > I added a node to select a local file to load instead, which could help if you are able to download it from here:
> > > https://huggingface.co/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/blob/main/open_clip_pytorch_model.bin
> > > to `ComfyUI/clip_vision` -folder
> > > ![image](https://private-user-images.githubusercontent.com/40791699/331589226-5e8cdcb1-8c54-4b78-aa61-c2d9da9804f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTM0MTMsIm5iZiI6MTcxNTk1MzExMywicGF0aCI6Ii80MDc5MTY5OS8zMzE1ODkyMjYtNWU4Y2RjYjEtOGM1NC00Yjc4LWFhNjEtYzJkOWRhOTgwNGYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzMzgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzOTNiMDEzZWE5ZGIzZmYwYTk2OWFkNjZlNGU0MTFkMGUwNzA3N2NjYjE5ZjFjZWYxNjFlNjVmZjQwYzQ4YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QoaO_RMfoBvx7_Sn8IhzstmuZpxutDyCu5Ofzm00iaI)
> > 
> > 
> > Dear kijai, I am sorry that I cannot find the node 'OpenCLIPVisionSelect'. Meanwhile, there is no access of 'opt_openclippath', as shown in the figure. Can you help me? Thanks you very much. ![image](https://private-user-images.githubusercontent.com/65980596/331616945-0e61313f-7e3f-46df-89c0-fbd87d456c1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTQyODcsIm5iZiI6MTcxNTk1Mzk4NywicGF0aCI6Ii82NTk4MDU5Ni8zMzE2MTY5NDUtMGU2MTMxM2YtN2UzZi00NmRmLTg5YzAtZmJkODdkNDU2YzFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzNTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NjA4YjFiZDNlMGMyNjk5MmRmM2RkNzJmYjQxMDU0ODEwYjQ4N2NlY2Y3MTY3NDc5YjljMGYwMmFjYWVmMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bm2B5ePc6PkeQSlJfGhN0c1lgXQkGr7gJEpVNKxCaT0)
> 
> I mean I literally just added it, so you would need to update this node pack.

Dear kijai, I am really sorry to disturb again. I just upadte all nodes in the manager. But I cannot find where is the node 'OpenCLIPVisionSelect', and there is still no 'opt_openclippath' button in the node 'DynamiCrafterModelLoader
'. Could you tell how to find the node 'OpenCLIPVisionSelect'? Many thanks.

**Comment by EvanZouQ** [comment]
Dear kijai, I am really sorry to disturb again. I just upadte all nodes in the manager. But I cannot find where is the node 'OpenCLIPVisionSelect', and there is still no 'opt_openclippath' button in the node 'DynamiCrafterModelLoader
'. Could you tell how to find the node 'OpenCLIPVisionSelect'? Many thanks.
![Uploading i2.jpg…]()

**Comment by kijai** [comment]
I added it 6h ago, it sounds like for some reason this node pack just hasn't updated. Maybe try re-installing?

**Comment by EvanZouQ** [comment]
Dear kijai, thanks for your assistance. Now, the updated codes are useful for me.

**Comment by kijai** [comment]
Clip models are now loaded with corresponding default Comfy nodes (or my download and load alternative), so it replaces this fix as well.
