### ISSUE TITLE
Latest version gives OOM

### ISSUE THREAD

**Issue by edwinzeng2005** [kijai/ComfyUI-DynamiCrafterWrapper#41]
After updating to latest version, I am getting out of memory issues. But I did managed to use it successfully many times before I updated this node to the latest version. Is there a way to reinstall the previous version of the node?

**Comment by edwinzeng2005** [comment]
I found the past commit and replaced the node folder.

**Comment by kijai** [comment]
This was probably because the new ToonCrafter code decoded all 16 frames at once, should be fixed in the latest version.
