### ISSUE TITLE
Does the recent refractor compromise output quality?

### ISSUE THREAD

**Issue by RokuDoan** [kijai/ComfyUI-DynamiCrafterWrapper#53]
After the recent update, it looks like the overall quality of animation seem to drop. Example below see a very minimal change in the background yet the generation seem to be frantic on its transition. On my testing 2 days before, it was a simply good side moving background transition. 

https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/25916165/9acc58d6-e79d-4e65-9857-01c09a09290e

Even if there is no background movement, the character movement also become much less consistent.

Is it possible to revert to how it works before?

**Comment by kijai** [comment]
I have not noticed anything like that, results like that always happened with some seeds in my experience, unless you are comparing to exact same seed?

**Comment by RokuDoan** [comment]
Can't really try same seed between update since I did not save the previous one. But retesting multiple seed did not improve this problem at all. But I pretty much nail consistent background output before this update.

**Comment by kijai** [comment]
Checked with the old commit `git checkout 0ec07f6 `
and there definitely is a difference, but nothing as drastic (or even worse quality wise) than what you are experiencing, background is almost exactly the same:

https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/40791699/123d4e88-338a-403c-97b6-de95dbfc9036

**Comment by kijai** [comment]
One thing I just noticed when comparing: if the prompt is left empty, then the results can be drastically different, but with any prompt they become similar.

**Comment by kijai** [comment]
I think I found the problem, latest version should fix it.

**Comment by RokuDoan** [comment]
Load CLIP model now causing this issue
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/25916165/1790cef7-8d8a-464e-b9a4-9fb7dba52107)


Trying to load ToonCrafter model to get its CLIP now also get HeaderTooLarge
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/25916165/f9955c5b-c9d7-4008-84b3-90ef1a8acfde)

**Comment by kijai** [comment]
> Load CLIP model now causing this issue
> ![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/25916165/1790cef7-8d8a-464e-b9a4-9fb7dba52107)
> 
> 
> Trying to load ToonCrafter model to get its CLIP now also get HeaderTooLarge
> ![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/25916165/f9955c5b-c9d7-4008-84b3-90ef1a8acfde)
> 

I don't know what the first error is about, but on the 2nd you don't actually have the ToonCrafter model selected.

**Comment by RokuDoan** [comment]
My bad, it looks like I tried to run the last workflow without noticing different model loaded in. The result seem to be pretty good now so I mark this one as closed.
