### ISSUE TITLE
Unable to export videos of larger size

### ISSUE THREAD

**Issue by idesign2018** [kijai/ComfyUI-DynamiCrafterWrapper#54]
I found the following error during use.
The following error occurs when using `dynamicrafter_1024_v1_bf16` model
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/42263070/08377739-61cf-454c-81dd-b82e89c02e74)

The following error occurs when using `dynamicrafter_512_interp_v1_bf16` model
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/42263070/c7f609d6-a510-4b26-8218-7799f0f7de4d)

When I want to export videos of larger and higher resolution, none of these three models `dynamicrafter_1024_v1_bf16`, `dynamicrafter_512_interp_v1_bf16`, `dynamicrafter_512_interp-fp16` work and errors appear
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/42263070/08c6493d-472c-4278-b968-31f386fdc818)

**Comment by idesign2018** [comment]
It seems that only 512*512px videos can be generated
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/42263070/ab09bc13-0eeb-4b95-945f-45a920165516)

**Comment by kijai** [comment]
This is still without xformers? Sadly it does use a lot more VRAM if xformers is not used.

**Comment by idesign2018** [comment]
> This is still without xformers? Sadly it does use a lot more VRAM if xformers is not used.这还是没有xformers吗？遗憾的是，如果不使用 xformers，它会使用更多的 VRAM。

xformers has been installed correctly and is running properly

After testing yesterday, you only need to change it to non-automatic to run it
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/42263070/73fc4f1d-5fab-4ee9-affa-2c7cc4b86928)
