### ISSUE TITLE
Unable to produce anything but moving brown mush

### ISSUE THREAD

**Issue by ProtoBelisarius** [kijai/ComfyUI-DynamiCrafterWrapper#57]
This is my workflow, pretty much like the example, same values at least. As I'm on AMD (running linux), I'm unable to install xformers and as such can't even test original decoder.  Does anyone have an idea why this happens?

![ComfyUI_temp_fmgbn_00003_](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/103048431/8bce8e44-3fd5-4a6e-b0d8-b36dca63799b)

![myWorkflow](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/103048431/20a5a132-0ebf-400e-bb9c-14265a09e913)

**Comment by kijai** [comment]
> This is my workflow, pretty much like the example, same values at least. As I'm on AMD (running linux), I'm unable to install xformers and as such can't even test original decoder.  Does anyone have an idea why this happens?
> 
> ![ComfyUI_temp_fmgbn_00003_](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/103048431/8bce8e44-3fd5-4a6e-b0d8-b36dca63799b)
> 
> ![myWorkflow](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/103048431/20a5a132-0ebf-400e-bb9c-14265a09e913)
> 

The model really can't do any other frame count than 16 currently, that result is directly because of that.

**Comment by ProtoBelisarius** [comment]
Oh yea, well error clearly between monitor and chair. I had tried it with 16 but too large of a resolution. Then I dropped it for faster testing and never tried 16 again. -____-
Thanks!

**Comment by thenightterorx** [comment]
I get mush even with completely default settings. Are there any additional reasons that could cause this?

**Comment by kacecarol** [comment]
same issue.
