### ISSUE TITLE
Re-downloading the tooncrafter_512_interp-fp16.safetensors...

### ISSUE THREAD

**Issue by XTRMsavage** [kijai/ComfyUI-DynamiCrafterWrapper#63]
I have already downloaded and saved the tooncrafter_512_interp-fp16.safetensors into ComfyUI\models\checkpoints. Why is the script tries to download it again?

**Comment by kijai** [comment]
The path it's looked from is `ComfyUI\models\checkpoints\dynamicrafter`

You can also just use the normal loading node too if you already have the model:

![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/40791699/e4edd4dd-bebe-49db-9d2c-3db6e175aedd)

**Comment by XTRMsavage** [comment]
> The path it's looked from is `ComfyUI\models\checkpoints\dynamicrafter`
> 
> You can also just use the normal loading node too if you already have the model:
> 
> ![image](https://private-user-images.githubusercontent.com/40791699/337575378-e4edd4dd-bebe-49db-9d2c-3db6e175aedd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDk4ODYsIm5iZiI6MTcxNzc0OTU4NiwicGF0aCI6Ii80MDc5MTY5OS8zMzc1NzUzNzgtZTRlZGQ0ZGQtYmViZS00OWRiLTlkMmMtM2RiNmUxNzVhZWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA4Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhODA3YjhmZjcwMjllZGI2N2QyMmY1ZDU2YzY4NzA5ZjNkZGFmNzk1NzI5ZGFmMDRhZjkyOTUyMzFmOTM3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HrHNX98JcOidczDWQitURCy2Enep8V2lpnXrE_P0MXA)

Thanks, worked.
