### ISSUE TITLE
tooncrafter is fading in/out between images

### ISSUE THREAD

**Issue by 3blackbar** [kijai/ComfyUI-DynamiCrafterWrapper#66]
I gave 4 input images, on huggingface i do this then theres no blurriness cause it goes from image 1 to 2, so how to make it identical her ?
I dont want fade into image2 then fade into image 3 etc... each image fades into another and its definitely not what99% of the users would want.
How to disable this? so it gets me exactly the output thats on reference image 2 ./3 /4  and not fadeed out 1image1 and 2 and 3 and 4 where images are spit.

Any way to let it render 1 to 2 only, then 2 to 3 only, then 3 to 4 only ? So there is no fade in/out cause it does not have image to fade into at the end ?
And i still would like to feed it multiple images not just 2 cause i know that if ill do it with 2 then i will get no fade in/out.
A switch would be nice.

Yeah image 1 to 2 is great but image 1 to 2 to 3 is pretty bad  cause it fades into 3rd image, can someone modify the node so it does not fade ?

Here is example, you can see how 2nd framew and 3d frame are TOGETHER in generated output - this is very wrong.
![0afe29b452](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/162857724/67f8aa79-c3b5-4708-b6d5-0ab211ab33a7)

And When it goes from 1st to 2nd  to 3rd it should not keep 2nd image in generated frames.

These are input frames 
![e3](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/162857724/7f63dbaa-9bb3-4ea1-8c7a-73c2f162fb0d)
![e2](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/162857724/9914e5ee-df88-4892-ad38-a9bafb06d691)
![e1](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/162857724/fbff6042-193a-4c01-a9ef-f5e8834567e4)

The best result i get when i do 1 to 2 , save it , then do 2 to 3 , save it , and 3 to 4 , save it , and manualy merge them  append one after another and remove last or first frames of each segment as theyre indentical on end and beginning  , i wish we could apply that workflow to this repo as well, it gets me this one below 

![exp1](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/162857724/c6002180-a258-4aa5-975d-55d87e3aba47)

Also when i use less than 16 in tooncrafter node for frames amount under eta - it gives me cracked noise .

+ resizing is borked - it moves the image left and so theyre not aligned properly

**Comment by kijai** [comment]
https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/40791699/0fd432cd-6f18-4b93-8a55-9c1f709fd19d

**Comment by 3blackbar** [comment]
yeah i did it like oyu before i read that and it is fine now theres no fade ins.
But huggingface worked with 10 frames ?
IS thre a chance to allow the node to accept lineart and color image like their demos did so it will do full color scene ?

**Comment by kijai** [comment]
The model itself can't work for 10 frames, it always has to generate 16, but it's of course possible to drop frames after the generation to retime the animation to your liking, I'm hoping to make some helper node for that.

They have not released the code for the sketch guidance or the colorization yet, still waiting on that to implement it.

**Comment by 3blackbar** [comment]
yeh i noticed that i just drops the frames on huggingface, and its the reason i got crap outputs sometimes.
Thanks for the info on sketch guidance, i hope they do and higher res model, now my workflow is tooncrafter then SUPIR to upscale cause it sticks to original lowres shape very well unlike other upscalers with img2img.
