### ISSUE TITLE
XFormers not available, it is required for ToonCrafter decoder. 

### ISSUE THREAD

**Issue by ai-rtist** [kijai/ComfyUI-DynamiCrafterWrapper#70]
XFormers not available, it is required for ToonCrafter decoder. Alternatively you can use a standard VAE Decode -node instead, but this has a negative effect on the image quality though.

**Comment by kijai** [comment]
What's unclear about that?

**Comment by kijai** [comment]
> > What's unclear about that?
> 
> I for some reason had to reinstall comfyui, and then this popped up again for me too, despite having xformers installed.

Well it simply uses comfy's xformers check, which passes if it's installed and can be imported, and that it's not disabled by the command line argument --disable-xformers.

**Comment by Dreamweaveress** [comment]
> > > What's unclear about that?
> > 
> > 
> > I for some reason had to reinstall comfyui, and then this popped up again for me too, despite having xformers installed.
> 
> Well it simply uses comfy's xformers check, which passes if it's installed and can be imported, and that it's not disabled by the command line argument --disable-xformers.

Thx! Tried to change that in main.py but could not find it there, you know to change the argument?
