### ISSUE TITLE
Sizes of tensors must match except in dimension 1. Expected size 768 but got size 1024 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by kikaruck** [kijai/ComfyUI-DynamiCrafterWrapper#72]
Sizes of tensors must match except in dimension 1. Expected size 768 but got size 1024 for tensor number 1 in the list.

**Comment by edwinzeng2005** [comment]
I have the same error if I use the updated version.

**Comment by kijai** [comment]
Need a lot more info, what's the workflow?

**Comment by edwinzeng2005** [comment]
Ok after trying the example workflow, it works again for the baseline.
But after trying the CIL version, I got this error instead.

Error occurred when executing DynamiCrafterI2V:
Sizes of tensors must match except in dimension 1. Expected size 128 but got size 40 for tensor number 1 in the list.

**Comment by edwinzeng2005** [comment]
The example workflow works now for the baseline model.
As for the CIL model, I had resized the image to 576x1024 without specifying the multiple-of input, setting it to zero.

**Comment by pf-w** [comment]
I also encountered this problem, but I used DownloadAndLoadCLIPVisionModel to download and load the recommended CLIP vision model, and used DownloadAndLoadCLIPModel to download and load the recommended CLIP model, and then it worked fine
