### ISSUE TITLE
No one is talking about how the example nodes are different from the actual broken nodes. 

### ISSUE THREAD

**Issue by Anomaly-TheMillennial** [kijai/ComfyUI-DynamiCrafterWrapper#74]
![2024-06-13 22 29 38](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/120991395/2bb7d15e-d12d-406b-bb94-627d3ba92653)

The example shows where you can just type the prompt into the node itself, but in reality it has a positive and negative clip embedding that only connects to incompatible nodes that cause a tensor mismatch. 

No one else has complained about this and I have ensured that my installation is not different from the current up-to-date.

Why is my node different from the example node and how do I rectify this issue?

**Comment by kijai** [comment]
The example video is old, but the actual example workflows included in the examples -folder are up to date.

**Comment by Anomaly-TheMillennial** [comment]
Thank you for illuminating my ignorance. I do have the examples in the folder.
