### ISSUE TITLE
Error occurred when executing DynamiCrafterI2V

### ISSUE THREAD

**Issue by Llin1028** [kijai/ComfyUI-DynamiCrafterWrapper#79]
Error occurred when executing DynamiCrafterI2V:

Resulting tensor containts NaNs. I'm unsure why this happens, changing step count and/or image dimensions might help.

File "I:\Artificialintelligence\app\!ComfyUI!\StableSwarmUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\Artificialintelligence\app\!ComfyUI!\StableSwarmUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\Artificialintelligence\app\!ComfyUI!\StableSwarmUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "I:\Artificialintelligence\app\!ComfyUI!\StableSwarmUI\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper-main\nodes.py", line 475, in process
assert not torch.isnan(samples).any().item(), "Resulting tensor containts NaNs. I'm unsure why this happens, changing step count and/or image dimensions might help."
![Snipaste_2024-06-21_12-04-59](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/131455899/15ad4d83-da3d-40dc-b6ad-7eefe818ff8f)

**Comment by jacksinofn** [comment]
我也报这个错误

**Comment by lyd85919** [comment]
Same problem. Has anyone solved it?

**Comment by edwinzeng2005** [comment]
Use even number of steps. Try 26, 28 or 30 steps.

**Comment by nomadoor** [comment]
![DynamicCrafterI2V](https://github.com/user-attachments/assets/55e3954c-8419-4f16-b2ad-4e7e46f979e5)
In my case, I was able to resolve the issue by setting the `dtype` of the Load DynamiCrafterModel node to `bf16`.
The `vae_dtype` of the DynamiCrafterI2V node didn’t cause any problems regardless of the setting.
Additionally, the image size and steps were not related to the issue at all.
