### ISSUE TITLE
[Enhancement] Improved motion

### ISSUE THREAD

**Issue by rkfg** [kijai/ComfyUI-DynamiCrafterWrapper#84]
There's a new method of putting more motion into the generated videos from the DynamiCrafter authors here: https://github.com/thu-ml/cond-image-leakage

Would be cool to implement it in this ComfyUI node!

**Comment by kijai** [comment]
Thanks for the heads-up!

It seems to be training technique, doesn't work on the existing models. I converted the one they released (512) and added support for it, along with their init_noises. The init noises being pre-calculated seems to force specific dimension to be used, which for the 512 version is 512x320.

Added comparison workflow too for testing, don't have more time right now to look into it though, seems to work as advertised when it comes to forcing motion at least.

**Comment by rkfg** [comment]
From what I understood it's both inference and training method, can be applied to the existing models with the help of the initial noise. Their description is pretty confusing. Thank you for such a quick response, I'll try it!

**Comment by kijai** [comment]
> How do I load the initial noise? There are some parameters missing it seems:
> ![2024-07-01_16-22-40](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/184066/fc3b070a-408f-4e08-a74a-179db434344d)
> ![2024-07-01_16-22-33](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/184066/a13bdbad-552b-467e-b670-26924af515a5)
> 
> I run CUI in a docker container so I mounted the `init_noises` directory into `models/checkpoints/init_noises`. It works without the `init_noise` input but then there's not much difference.

The noise files are tiny so I just included them in the git repo, the init noise node loads them automatically based on the checkpoint name.

**Comment by rkfg** [comment]
But then it's not possible to change the `M` and `analytic_init` parameters.

**Comment by kijai** [comment]
> But then it's not possible to change the `M` and `analytic_init` parameters.

The LoadInitNoise loads the matching noise file, it's passed along with the parameters to the sampler. If the "analytic_init" is disabled, random noise is used instead. In both cases, if the init_noise input is connected, the M parameter is used to set the starting timestep.

**Comment by rkfg** [comment]
Yes, that's what I'm trying to do in the image above and it doesn't load the file. There's an input called "model" and I can't leave it blank: 
![2024-07-01_16-55-13](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/184066/33dea2b5-1771-4db2-8034-9f5c66b8ad0a)

**Comment by kijai** [comment]
The model input is required because it reads some parameters from the model, you just input the loaded DynamiCrafter node into that.

**Comment by rkfg** [comment]
Thank you, now it works! It's really not obvious that the noise is automatically loaded and you need to provide the model to both the sampler and the loader.

**Comment by kijai** [comment]
They just released the 1024 CIL model too, added it as well.

**Comment by rkfg** [comment]
When running it with `init_noise` I get: 
```
Error occurred when executing DynamiCrafterI2V:

Sizes of tensors must match except in dimension 1. Expected size 72 but got size 104 for tensor number 1 in the list.
...
File "/app/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/models/ddpm3d.py", line 738, in forward
xc = torch.cat([x] + c_concat, dim=1)
```
The noise files are in place and it worked for 512 but not for 1024 CIL.

**Comment by kijai** [comment]
The image dimensions must match the init noise dimensions, which is the
default 1024x576 (I think)

**Comment by rkfg** [comment]
Huh, it's more strict than expected then. The non-CIL versions accept any sizes though they perform best when it matches the training resolution. Interesting. Yes, it works with explicit resize.

**Comment by edwinzeng2005** [comment]
My image size is 720x1280 portrait.
I had noticed that the example workflow uses the resize-image node with the multiple-of parameter as 64.
Setting it to zero, while manually ensuring a 9:16 or 16:9 ratio works for me.

**Comment by edwinzeng2005** [comment]
My image input is of size 720x1280.
I had to rotate the image first, then resize the image to 576x1024 without specifying the multiple-of input, setting it to zero.
So it can run the node successfully without any errors. But if I did not rotate the image, the error will show up.

Might be a good idea to ask the author if rotated portrait inputs would work similarly to landscape ones.

**Comment by edwinzeng2005** [comment]
Ok so the reply was that it should work with portrait images as well.
I think there might be still a bug somewhere that prevents the generation from using an image in portrait resolution (576x1024).

**Comment by edwinzeng2005** [comment]
I am beginning to understand how much to adjust the M value. Perhaps the image rotation might actually be the correct way to get the portrait resolution to work. I might be just missing the correct M value.

**Comment by edwinzeng2005** [comment]
Thanks for the suggestion! I will try it out too.

**Comment by edwinzeng2005** [comment]
There was an update to several files over at the CIL github a few hours ago.

**Comment by kijai** [comment]
> There was an update to several files over at the CIL repo a few hours ago.

Yeah, but nothing I hadn't already implemented, and rest was mostly cleanup.

**Comment by rkfg** [comment]
Looks like the current CIL models in this wrapper do have watermarks despite the name. I'm not sure what's wrong but the CIL authors released the watermark-free models here: https://huggingface.co/GraceZhao/DynamiCrafter-CIL-512-no-watermark/tree/main and https://huggingface.co/GraceZhao/DynamiCrafter-CIL-1024/tree/main

**Comment by kijai** [comment]
> Looks like the current CIL models in this wrapper do have watermarks despite the name. I'm not sure what's wrong but the CIL authors released the watermark-free models here: https://huggingface.co/GraceZhao/DynamiCrafter-CIL-512-no-watermark/tree/main and https://huggingface.co/GraceZhao/DynamiCrafter-CIL-1024/tree/main

Yes...those are the models I'm using. Their example videos of the 1024 also have huge watermarks:

https://github.com/thu-ml/cond-image-leakage/tree/main/assets/1024demos

Also I specifically took the "no-watermark" version of the 512 model from their HF too, it should rather be called "less watermark" I guess.

**Comment by edwinzeng2005** [comment]
The 1024 model was re-uploaded but I am not sure if it still has watermarks.

**Comment by edwinzeng2005** [comment]
@kijai 
We will need an update to the pruned 1024 model, so I can further test it again for watermarks.
The author has also asked for some example outputs that has watermarks as well.

**Comment by edwinzeng2005** [comment]
Ok it is watermark-free for the first result from the 10gb model.
We will need the pruned model to confirm further results as the 10gb model is too slow.

**Comment by zhuhz22** [comment]
> > Looks like the current CIL models in this wrapper do have watermarks despite the name. I'm not sure what's wrong but the CIL authors released the watermark-free models here: https://huggingface.co/GraceZhao/DynamiCrafter-CIL-512-no-watermark/tree/main and https://huggingface.co/GraceZhao/DynamiCrafter-CIL-1024/tree/main
> 
> Yes...those are the models I'm using. Their example videos of the 1024 also have huge watermarks:
> 
> https://github.com/thu-ml/cond-image-leakage/tree/main/assets/1024demos
> 
> Also I specifically took the "no-watermark" version of the 512 model from their HF too, it should rather be called "less watermark" I guess.

Hi @kijai ,sorry for the confusion.Now both the 512 and 1024 model uploaded are watermark-free.

**Comment by kijai** [comment]
> > > Looks like the current CIL models in this wrapper do have watermarks despite the name. I'm not sure what's wrong but the CIL authors released the watermark-free models here: https://huggingface.co/GraceZhao/DynamiCrafter-CIL-512-no-watermark/tree/main and https://huggingface.co/GraceZhao/DynamiCrafter-CIL-1024/tree/main
> > 
> > 
> > Yes...those are the models I'm using. Their example videos of the 1024 also have huge watermarks:
> > https://github.com/thu-ml/cond-image-leakage/tree/main/assets/1024demos
> > Also I specifically took the "no-watermark" version of the 512 model from their HF too, it should rather be called "less watermark" I guess.
> 
> Hi @kijai ,sorry for the confusion.Now both the 512 and 1024 model uploaded are watermark-free.

Alright, thank you for clarifying, and for the models!

Pruned them again and updated the auto download to point at the new versions:

https://huggingface.co/Kijai/DynamiCrafter_pruned
