### ISSUE TITLE
missing 2 required positional arguments: 'dtype' and 'device'

### ISSUE THREAD

**Issue by zsmjts** [kijai/ComfyUI-DynamiCrafterWrapper#85]
![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/126183834/f8840345-47d7-412c-96d4-530693b81125)
Please , tell me what went wrong~

**Comment by kijai** [comment]
My mistake, forgot to update the old, normal model loader node. Fixed now.
