### ISSUE TITLE
Error: type object 'manual_cast' has no attribute 'Conv1d' in DynamiCrafter wrapper

### ISSUE THREAD

**Issue by rslosch** [kijai/ComfyUI-DynamiCrafterWrapper#86]
Description:
I'm encountering an error when trying to use the DynamiCrafter wrapper with ComfyUI. The error occurs when attempting to load the DynamiCrafter model.

Error message:
Error occurred when executing DownloadAndLoadDynamiCrafterModel: type object 'manual_cast' has no attribute 'Conv1d'

File "/workspace/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/workspace/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/nodes.py", line 132, in loadmodel
self.model = instantiate_from_config(model_config)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/utils/utils.py", line 33, in instantiate_from_config
return get_obj_from_str(config["target"])(**config.get("params", dict()))
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/models/ddpm3d.py", line 706, in __init__
super().__init__(*args, **kwargs)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/models/ddpm3d.py", line 398, in __init__
super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/models/ddpm3d.py", line 85, in __init__
self.model = DiffusionWrapper(unet_config, conditioning_key)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/models/ddpm3d.py", line 722, in __init__
self.diffusion_model = instantiate_from_config(diff_model_config)
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/utils/utils.py", line 33, in instantiate_from_config
return get_obj_from_str(config["target"])(**config.get("params", dict()))
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/modules/networks/openaimodel3d.py", line 393, in __init__
TemporalTransformer(
File "/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/modules/attention.py", line 334, in __init__
self.proj_in = ops.Conv1d(in_channels, inner_dim, kernel_size=1, stride=1, padding=0)

Environment:
- ComfyUI version: latest
- DynamiCrafter wrapper version: version = "1.0.2"
- Python version: Python 3.10.12
- Operating System: Ubuntu 22.04.3 LTS

Steps to reproduce:
1. Attempt to load the DynamiCrafter model in ComfyUI

Additional information:
- The error occurs in the file: `/workspace/ComfyUI/custom_nodes/ComfyUI-DynamiCrafterWrapper/lvdm/modules/attention.py`, line 334
- The specific line causing the error is: `self.proj_in = ops.Conv1d(in_channels, inner_dim, kernel_size=1, stride=1, padding=0)`
- In the codebase, `ops` is defined as: `ops = comfy.ops.manual_cast`
- The `manual_cast` class in `comfy/ops.py` does not include a `Conv1d` definition. It includes other types like `Conv2d` and `Conv3d`, but `Conv1d` is missing.

Attempted solutions:
No solutions have been attempted yet, but I've investigated the codebase to locate the source of the error.

Questions:
1. Is `Conv1d` supposed to be part of the `manual_cast` class?
2. If not, where should `Conv1d` be imported from for use with the DynamiCrafter wrapper?
3. Are there any version compatibility issues between ComfyUI and the DynamiCrafter wrapper that could be causing this?
4. Should the DynamiCrafter wrapper be updated to use `Conv2d` or `Conv3d` instead of `Conv1d`?

Any assistance in resolving this issue would be greatly appreciated. Let me know if you need any additional information.
s/o claude sonnet lol

**Comment by xiexiaobo135** [comment]
me too, The latest plugin I just installed also reported this error after running

**Comment by r0zh** [comment]
> That's weird, are you sure your Comfy is up to date? Currently there absolutely is Conv1d in the ops among the others:
> 
> ![image](https://private-user-images.githubusercontent.com/40791699/345547096-aefa3357-819c-411b-b3be-374ed345122b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjgyNzIsIm5iZiI6MTcyMDM2Nzk3MiwicGF0aCI6Ii80MDc5MTY5OS8zNDU1NDcwOTYtYWVmYTMzNTctODE5Yy00MTFiLWIzYmUtMzc0ZWQzNDUxMjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE1NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNDAxYmFjOGI1YTE3Mzk3Mzg5ZTIzYjFkMzMwM2VlZmM2YzVhM2Y2OTFhYjM5Y2UxOTJlOTUzZjQ3YmI4YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.omyG7z06g0YmWaApEHEYpskkUgzTuA1K-nCFS4Vq4ek)

Updating ComfyUI solved it for me, thanks!
