### ISSUE TITLE
Error occurred when executing ToonCrafterInterpolation:  No operator found for `memory_efficient_attention_forward` with inputs:

### ISSUE THREAD

**Issue by Muxiaorong77** [kijai/ComfyUI-DynamiCrafterWrapper#87]
Error occurred when executing ToonCrafterInterpolation:

No operator found for `memory_efficient_attention_forward` with inputs:
query : shape=(80, 2048, 1, 64) (torch.float16)
key : shape=(80, 2048, 1, 64) (torch.float16)
value : shape=(80, 2048, 1, 64) (torch.float16)
attn_bias :
p : 0.0
`decoderF` is not supported because:
xFormers wasn't build with CUDA support
attn_bias type is
operator wasn't built - see `python -m xformers.info` for more info
`flshattF@0.0.0` is not supported because:
xFormers wasn't build with CUDA support
operator wasn't built - see `python -m xformers.info` for more info
`cutlassF` is not supported because:
xFormers wasn't build with CUDA support
operator wasn't built - see `python -m xformers.info` for more info
`smallkF` is not supported because:
max(query.shape[-1] != value.shape[-1]) > 32
xFormers wasn't build with CUDA support
dtype=torch.float16 (supported: {torch.float32})
operator wasn't built - see `python

**Comment by kijai** [comment]
Your xformers install isn't correct, either completely uninstall it or try re-installing. How to do that depends on your comfy install type and pytorch version though.
