### ISSUE TITLE
Deep Fried Output

### ISSUE THREAD

**Issue by jelling** [kijai/ComfyUI-DynamiCrafterWrapper#88]
I'm probably doing something dumb but the final video looks like this:

![Screen Shot 2024-07-05 at 5 26 26 PM](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/1887486/75d503ef-60bd-441d-89d2-cea14a00fc2c)

With these 2 key frames:

![cesaron keyframes copy 1](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/1887486/0ac918b6-8f59-4e6b-b0ef-8822c189781d)
![cesaron keyframes copy 2](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/1887486/5737e354-b7e1-419b-9e0c-bd0cad9a9545)

Any ideas?

**Comment by kijai** [comment]
Using which model/workflow?

**Comment by jelling** [comment]
I figured it out. I needed 
[vae-ft-mse-840000-ema-pruned.safetensors](https://huggingface.co/stabilityai/sd-vae-ft-mse-original/blob/main/vae-ft-mse-840000-ema-pruned.safetensors) as the VAE.
