### ISSUE TITLE
Garbage interpolation at frame counts <16

### ISSUE THREAD

**Issue by phr00t** [kijai/ComfyUI-DynamiCrafterWrapper#9]
Is there any way to successfully run interpolation with less than 16 frames? I see the option for frame count, but it seems like 16 is the only selection that works. If I try 4 or 8 frames, it is just a noisy mess not matter how many steps are used:

![image](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/5983470/782eb37a-3083-4263-b9e2-aca4e3d638ea)

Is there a trick to getting fewer frames to work? It is sooooo much faster at generation with fewer frames.

**Comment by kijai** [comment]
No idea, probably not, it's not trained for that.
