### ISSUE TITLE
Why does the video I generated shake? I want to generate a still camera, how can I do it?

### ISSUE THREAD

**Issue by chenminglin** [kijai/ComfyUI-DynamiCrafterWrapper#90]
![WX20240707-190643@2x](https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/4445873/36dd4c57-aa7c-4ccd-b082-7f9af5788f10)

https://github.com/kijai/ComfyUI-DynamiCrafterWrapper/assets/4445873/c4024bcb-68b4-49dc-aa6e-35c9cccaa730

**Comment by kijai** [comment]
Just keep trying different seeds and prompts, there's no way to control the camera specifically like that, mostly it's just random what it wants to do.

**Comment by chenminglin** [comment]
你好！我是陈铭霖，我已收到你的邮件，我会尽快回复处理。

**Comment by chenminglin** [comment]
thank you
