### ISSUE TITLE
ToonCrafter_with_SketchGuidance by  mattyamonaca

### ISSUE THREAD

**Issue by zafirexd** [kijai/ComfyUI-DynamiCrafterWrapper#93]
https://github.com/mattyamonaca/ToonCrafter_with_SketchGuidance

**Comment by kijai** [comment]
Yes I have seen it, I'm currently away on a holiday trip so it'll have to wait a bit, will add it once I return.

**Comment by FemBoxbrawl** [comment]
Can't wait!!!!

**Comment by kijai** [comment]
I have the initial support working and implemented already, it can replicate what that repo does at least:

https://github.com/user-attachments/assets/5f3ce729-0e2c-49b5-a724-b9a5588ef88f

**Comment by GiusTex** [comment]
Will you add it to the develop branch, or are you waiting for more tests? For now I don't see any updates in the 3 branches

**Comment by kijai** [comment]
> Will you add it to the develop branch, or are you waiting for more tests? For now I don't see any updates in the 3 branches

I added it yesterday to main branch, today fixed some bugs.

**Comment by FemBoxbrawl** [comment]
> > Will you add it to the develop branch, or are you waiting for more tests? For now I don't see any updates in the 3 branches
> 
> I added it yesterday to main branch, today fixed some bugs.

Could you create an example workflow please?

**Comment by GiusTex** [comment]
> Could you create an example workflow please?

![Sketch_Reference](https://github.com/user-attachments/assets/6cadf6d7-2480-44c9-adb8-f924e9022f5e)

![Sketch_Reference_Screen](https://github.com/user-attachments/assets/ebff699e-2d1a-4aa7-830b-3f886fcae32e)

[Sketch_Reference_workflow.json](https://github.com/user-attachments/files/16322396/Sketch_Reference_workflow.json)

**Comment by FemBoxbrawl** [comment]
> > Could you create an example workflow please?
> 
> ![Sketch_Reference](https://private-user-images.githubusercontent.com/112352961/350724714-6cadf6d7-2480-44c9-adb8-f924e9022f5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MTExODYsIm5iZiI6MTcyMTUxMDg4NiwicGF0aCI6Ii8xMTIzNTI5NjEvMzUwNzI0NzE0LTZjYWRmNmQ3LTI0ODAtNDRjOS1hZGI4LWY5MjRlOTAyMmY1ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQyMTI4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOThmMDQ1ZjRiZWZhZDQyOTlkYWVjYjk3YWMxNTg0NjQwOTk2NmI4ZjMzNDliYTg5ZWUxZTkwNjgyNzZmMmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yPkJ8GmkxOe4OB8jrWtgCf7Nk2oyB535kiELJ5nZNRY) [ ](https://private-user-images.githubusercontent.com/112352961/350724714-6cadf6d7-2480-44c9-adb8-f924e9022f5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MTExODYsIm5iZiI6MTcyMTUxMDg4NiwicGF0aCI6Ii8xMTIzNTI5NjEvMzUwNzI0NzE0LTZjYWRmNmQ3LTI0ODAtNDRjOS1hZGI4LWY5MjRlOTAyMmY1ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQyMTI4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOThmMDQ1ZjRiZWZhZDQyOTlkYWVjYjk3YWMxNTg0NjQwOTk2NmI4ZjMzNDliYTg5ZWUxZTkwNjgyNzZmMmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yPkJ8GmkxOe4OB8jrWtgCf7Nk2oyB535kiELJ5nZNRY) ![Sketch_Reference](https://private-user-images.githubusercontent.com/112352961/350724714-6cadf6d7-2480-44c9-adb8-f924e9022f5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MTExODYsIm5iZiI6MTcyMTUxMDg4NiwicGF0aCI6Ii8xMTIzNTI5NjEvMzUwNzI0NzE0LTZjYWRmNmQ3LTI0ODAtNDRjOS1hZGI4LWY5MjRlOTAyMmY1ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQyMTI4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOThmMDQ1ZjRiZWZhZDQyOTlkYWVjYjk3YWMxNTg0NjQwOTk2NmI4ZjMzNDliYTg5ZWUxZTkwNjgyNzZmMmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yPkJ8GmkxOe4OB8jrWtgCf7Nk2oyB535kiELJ5nZNRY) [ ](https://private-user-images.githubusercontent.com/112352961/350724714-6cadf6d7-2480-44c9-adb8-f924e9022f5e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MTExODYsIm5iZiI6MTcyMTUxMDg4NiwicGF0aCI6Ii8xMTIzNTI5NjEvMzUwNzI0NzE0LTZjYWRmNmQ3LTI0ODAtNDRjOS1hZGI4LWY5MjRlOTAyMmY1ZS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQyMTI4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOThmMDQ1ZjRiZWZhZDQyOTlkYWVjYjk3YWMxNTg0NjQwOTk2NmI4ZjMzNDliYTg5ZWUxZTkwNjgyNzZmMmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yPkJ8GmkxOe4OB8jrWtgCf7Nk2oyB535kiELJ5nZNRY)
> 
> ![Sketch_Reference_Screen](https://private-user-images.githubusercontent.com/112352961/350724704-ebff699e-2d1a-4aa7-830b-3f886fcae32e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MTExODYsIm5iZiI6MTcyMTUxMDg4NiwicGF0aCI6Ii8xMTIzNTI5NjEvMzUwNzI0NzA0LWViZmY2OTllLTJkMWEtNGFhNy04MzBiLTNmODg2ZmNhZTMyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQyMTI4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzI2NDJjOWNlOTZmODEyMGI4ZDJkNTk4MDRiMzQwNDk0ZTkyZTQyZGQwN2Y0NzU2OTBhZWFkYWI5MjlkMzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FRs8pHFmbiaJ4GizNbp66V2U42ZGOMmCF2XNqmWsqts)
> 
> [Sketch_Reference_workflow.json](https://github.com/user-attachments/files/16322396/Sketch_Reference_workflow.json)

thank you :D

**Comment by GiusTex** [comment]
You're welcome 👍🏻
Do some tests to see if you can remove the reflection, maybe it depends on the model, or on controlnet, I dunno.
Edit:
Ah the second note on the right is a leftover from my previous workflow, it had thoughts etc, don't mind it.

**Comment by FemBoxbrawl** [comment]
> You're welcome 👍🏻 Do some tests to see if you can remove the reflection, maybe it depends on the model, or on controlnet, I dunno. Edit: Ah the second note on the right is a leftover from my previous workflow, it had thoughts etc, don't mind it.


Hey, I got this error trying to get it to work, do you know how to fix this? this may have something to do with a note you left on your workflow with Controlnet changing the resolution

![Screenshot 2024-09-02 020935](https://github.com/user-attachments/assets/65b3c385-1de2-422e-bd28-8d321070f2c4)
![Screenshot 2024-09-02 021050](https://github.com/user-attachments/assets/4ad0466d-1bd7-4899-8a69-0ed5624e5fa9)

**Comment by GiusTex** [comment]
Use Image Resize (or a similar node) to set the same size for the controlnet video and the keyframes images; maybe you didn't use it on one of them and they had different sizes

**Comment by FemBoxbrawl** [comment]
> Use Image Resize (or a similar node) to set the same size for the controlnet video and the keyframes images; maybe you didn't use it on one of them and they had different sizes

Okay, I figured it out. I simply need the original size to be 512x320, I usually do 512x288, but it messes stuff up. So it's all good.

**Comment by kjhyhy6765** [comment]
I'm getting the same error but different numbers, both of them are connected to a resize node? 
RuntimeError: The size of tensor a (16) must match the size of tensor b (60) at non-singleton dimension 0

![Image](https://github.com/user-attachments/assets/73aae8e6-d950-400c-93b0-fb099896d45c)

**Comment by GiusTex** [comment]
> I'm getting the same error

I think the controlnet apply needs the original size (512x320), based on FemBoxbrawl's reply; I usually didn't use it and tooncrafter worked fine with custom size, so I suppose it must be the controlnet apply that doesn't support custom sizes

**Comment by kjhyhy6765** [comment]
> > I'm getting the same error
> 
> I think the controlnet apply needs the original size (512x320), based on FemBoxbrawl's reply; I usually didn't use it and tooncrafter worked fine with custom size, so I suppose it must be the controlnet apply that doesn't support custom sizes

Do you mean changing the image resolution now or a variable on one of the nodes? I've changed the images to 512x320 and still same error. also the image res before was 512x512

**Comment by GiusTex** [comment]
> also the image res before was 512x512

I know, I saw it
> Do you mean changing the image resolution

This, yes
> I've changed the images to 512x320 and still same error

Uhm, I don't know then.. Did you try without controlnet apply? Just to check if the problem is tied to it

**Comment by kjhyhy6765** [comment]
YT

> > also the image res before was 512x512
> 
> I know, I saw it
> 
> > Do you mean changing the image resolution
> 
> This, yes
> 
> > I've changed the images to 512x320 and still same error
> 
> Uhm, I don't know then.. Did you try without controlnet apply? Just to check if the problem is tied to it

Yes! I have unplugged the DynamicCrafter ControlnetApply socket from the interp node and it is has succesfuly loaded and I see a output video but got the msg: ImageConcatMulti
Sizes of tensors must match except in dimension 2. Expected size 60 but got size 48 for tensor number 1 in the list.

**Comment by GiusTex** [comment]
Can you send a screen of the nodes around the problem? To have a bit of context. The whole workflow is fine too if it isn't too big

**Comment by kjhyhy6765** [comment]
> Can you send a screen of the nodes around the problem? To have a bit of context. The whole workflow is fine too if it isn't too big

[RobotWorkflow.json](https://github.com/user-attachments/files/18496296/RobotWorkflow.json) here, basically the same as the posted workflow, just changed the variables on the resize images from 512 to 320 and turned the preprocessor to none

**Comment by GiusTex** [comment]
![Image](https://github.com/user-attachments/assets/038b5f10-097d-4af9-80f5-665d0fc49d4e)

I changed `divisible by` 64 into 2 (to get an image size as similar as possible to the original), and unchecked `keep proprtion` (otherwise you probably won't ever get same images and video sizes), and I got a video without problems. (Only thing to mention was that I had to queue the video 2 times, the first the `(down)load model` node gave a problem, while the second time it worked fine)

**Comment by kjhyhy6765** [comment]
> ![Image](https://github.com/user-attachments/assets/038b5f10-097d-4af9-80f5-665d0fc49d4e)
> 
> I changed `divisible by` 64 into 2 (to get an image size as similar as possible to the original), and unchecked `keep proprtion` (otherwise you probably won't ever get same images and video sizes), and I got a video without problems. (Only thing to mention was that I had to queue the video 2 times, the first the `(down)load model` node gave a problem, while the second time it worked fine)

Got the error Sizes of tensors must match except in dimension 2. Expected size 60 but got size 48 for tensor number 1 in the list.
on image concatenate multi? 

[![Image](https://github.com/user-attachments/assets/a54f84bc-b2e4-4f44-8105-25b1d826766e)
](https://cdn.discordapp.com/attachments/1137366344686370916/1331375078289707068/image.png?ex=6791632a&is=679011aa&hm=72e0785c77139d204de238bf97f6bb4af7c32127d617e06b4efd9d82ee0402b0&format=webp&quality=lossless)

. ButAlso when this works, will it mean I can change the resolution to something like 512x512 again?

**Comment by GiusTex** [comment]
> on image concatenate multi

Uncheck `match image size`

**Comment by GiusTex** [comment]
> But Also when this works, will it mean I can change the resolution to something like 512x512 again?

Yes without controlnet apply; I haven't tested with it (attached/enabled in the workflow) so I don't know, but I think it could work

**Comment by kjhyhy6765** [comment]
> > But Also when this works, will it mean I can change the resolution to something like 512x512 again?
> 
> Yes without controlnet apply; I haven't tested with it so I don't know, but I think it could work

Still got the same error. what exactly does the image concatenate multi do? if i already have the previous video combine already rendered. is it a higher quality version or something after going through it to the second video combine?

**Comment by GiusTex** [comment]
> what exactly does the image concatenate multi do

you can remove it, that node just aligns images next to each other, I put it to create a comparison between the guide video, the first and last frame, and the output video, if you remove it it only shows the output video

**Comment by kjhyhy6765** [comment]
> > what exactly does the image concatenate multi do
> 
> you can remove it, that node just aligns images next to each other, I put it to create a comparison between the guide video, the first and last frame, and the output video, if you remove it it only shows the output video

Alright awesesome so I'm good. Thanks 100 Mr.Tex youre a lifeSAVER!

**Comment by jelling** [comment]
>  Do some tests to see if you can remove the reflection, maybe it depends on the model, or on controlnet, I dunno. 

Did you ever find out where the reflection is coming from? Thanks for putting together the example btw. 

Edit: it's definitely the ControlNet. Even using a matte image had the issue.
