### ISSUE TITLE
The model takes a long time to load. What is the reason

### ISSUE THREAD

**Issue by fanmingfei** [kijai/ComfyUI-DynamiCrafterWrapper#94]
<img width="502" alt="image" src="https://github.com/user-attachments/assets/bb8a627c-60ae-41ab-a0ce-d7d222a42823">

**Comment by kijai** [comment]
How long is that? It's only couple of seconds for me.

**Comment by fanmingfei** [comment]
4060Ti   10minus + ....

**Comment by kijai** [comment]
That's weird, do you have `accelerate` installed?

**Comment by fanmingfei** [comment]
Yes, I have installed accelerate.

When loading the model, it takes a long time for both the RAM and the VRAM to load.

After executing this node, it takes a few minutes(5min) to see the VRAM slowly rise to 5GB. The whole process takes about ten minutes.

Once the model is loaded into the VRAM, after generating a video, the VRAM usage drops, sometimes to just 100MB. However, there is no need to reload the model when generating again.

**Comment by kijai** [comment]
Only reason I can imagine for that is that your VRAM or RAM is full and it's swapping to disk, if that's not the case I honestly have no idea as I've never seen anything like that.

**Comment by fanmingfei** [comment]
```
top - 09:28:19 up 6 days, 18:05,  2 users,  load average: 1.02, 0.57, 0.24
Tasks: 244 total,   1 running, 243 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.2 us,  0.0 sy,  0.0 ni, 93.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  3.2/64298.1  [|||                                                                                                 ]
MiB Swap:  1.4/4096.0   [|                                                                                                   ]

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1262550 root      20   0   47.3g   1.6g 996024 S 100.3   2.6   3:52.83 pt_main_thread
```

CPU 100%  
VIRT 47 G  But it's not reflected in memory, same as the other models

**Comment by fanmingfei** [comment]
I updated accelerate@0.32.1, worked.
