### ISSUE TITLE
 execution error

### ISSUE THREAD

**Issue by suifeng1221** [kijai/ComfyUI-DynamiCrafterWrapper#95]
![5fc179fb50ecdcb259684432ab3ae75](https://github.com/user-attachments/assets/d3956344-a42b-417a-9292-f3003b3b3038)
![3f7b132698988a372245deb193007d5](https://github.com/user-attachments/assets/af289edf-59ed-495b-9fb9-95e7a6a8ff74)

**Comment by kijai** [comment]
Should be fixed now
